# Exclude patterns
# Note: Liquid template variables (\{\{.*\}\}) are handled in .lycheeignore
exclude = [
    "/assets/**/*",
    "https://stackoverflow.com/*",
    "https://kipac.stanford.edu/"
]

# Max retries for requests
max_retries = 3

# Timeout in seconds
timeout = 20 